/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jframeform;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CDMFP
 */
public class JFrameForm extends javax.swing.JFrame {

    static ArrayList<PreguntaRespuesta> lista=null;
    static int indice_pregunta=0;
    static int puntuacion=0;
    
    /**
     * Creates new form JFrameForm
     */
    public JFrameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pre_pregunta = new javax.swing.JLabel();
        txt_respuesta = new javax.swing.JTextField();
        boton_comprobar = new javax.swing.JButton();
        puntos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pre_pregunta.setText("Pregunta1");

        txt_respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_respuestaActionPerformed(evt);
            }
        });

        boton_comprobar.setText("Comprobar");
        boton_comprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_comprobarMouseClicked(evt);
            }
        });
        boton_comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comprobarActionPerformed(evt);
            }
        });
        boton_comprobar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boton_comprobarKeyPressed(evt);
            }
        });

        puntos.setText("Puntuacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_respuesta)
                    .addComponent(pre_pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_comprobar)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pre_pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(txt_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(boton_comprobar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_respuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_respuestaActionPerformed

    private void boton_comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comprobarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_comprobarActionPerformed

    private void boton_comprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_comprobarMouseClicked
        comprobarRespuesta();
    }//GEN-LAST:event_boton_comprobarMouseClicked

    private void boton_comprobarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boton_comprobarKeyPressed
        // TODO add your handling code here:
        int tecla=evt.getKeyCode();
        if(tecla==10)
        {
            comprobarRespuesta();
        }
    }//GEN-LAST:event_boton_comprobarKeyPressed
    
    private void comprobarRespuesta()
    {
        // TODO add your handling code here:
        String respuesta=txt_respuesta.getText();
        //String pregunta=pre_pregunta.getText();
        //PreguntaRespuesta p=new PreguntaRespuesta(pregunta, respuesta);
        String respuesta_correcta=lista.get(indice_pregunta).getRespuesta();
        if(respuesta.equalsIgnoreCase(respuesta_correcta))
        {
            puntuacion++;
            JOptionPane.showMessageDialog(rootPane, "Enhorabuena");
            actualizarPuntuacion();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Has fallado, la respuesta correcta es "+respuesta_correcta);
        }
        if(indice_pregunta<lista.size()-1)
        {
        indice_pregunta++;
        mostrarPregunta();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Gracias por jugar, tu puntuacion es: "+puntuacion);
        }
        
    }
    
    private static void actualizarPuntuacion()
    {
        puntos.setText(String.valueOf(puntuacion));
    }
    
    public static void mostrarPregunta()
    {
        PreguntaRespuesta p=lista.get(indice_pregunta);
        String texto_pregunta=p.getPregunta();
        pre_pregunta.setText(texto_pregunta);
        txt_respuesta.setText("");//Dejar en blanco despues de una respuesta.
        txt_respuesta.requestFocusInWindow();//Para que el cursos se quede en txt_respuesta.
        
        
        //indice_pregunta=indice_pregunta+1;
                
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            //int puntuacion=0;
            //ArrayList<PreguntaRespuesta> lista_preguntas=LectorFichero.devolverPreguntas();
            
            lista=LectorFichero.devolverPreguntas();
           
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameForm().setVisible(true);
                
                mostrarPregunta(); //en el label de pregunta saca el texto de la preugnta que toque (y toca lista.get(indice_pregunta).
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton boton_comprobar;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JLabel pre_pregunta;
    private static javax.swing.JLabel puntos;
    private static javax.swing.JTextField txt_respuesta;
    // End of variables declaration//GEN-END:variables
}
