/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sumaenpantalla;

import javax.swing.JOptionPane;

/**
 *
 * @author CDMFP
 */
public class Pantalla extends javax.swing.JFrame {
public static Operacion op=null;
static int puntuacion=0;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operando1 = new javax.swing.JLabel();
        operando2 = new javax.swing.JLabel();
        txt_suma = new javax.swing.JLabel();
        btn_comprobar = new javax.swing.JButton();
        lbl_puntuacion = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        operando1.setText("X");

        operando2.setText("Y");
        operando2.setToolTipText("");

        txt_suma.setText("+");

        btn_comprobar.setText("Comprobar");
        btn_comprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_comprobarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_comprobar)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_puntuacion)
                        .addGap(120, 120, 120))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(operando2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(operando1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txt_suma))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_puntuacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operando1)
                .addGap(15, 15, 15)
                .addComponent(txt_suma)
                .addGap(10, 10, 10)
                .addComponent(operando2)
                .addGap(31, 31, 31)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btn_comprobar)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_comprobarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_comprobarMouseClicked
        // TODO add your handling code here:
        //1-Coger lo que ha pueesto el tio
        //2-Coger la respuesta correcta (op)
        //3-Comparar
        //Si OK->Sumpo punto,felicito->Saco otra op.
        //
        comprobarOperacion();
        jTextField1.setText("");
    }//GEN-LAST:event_btn_comprobarMouseClicked

    private void comprobarOperacion()
    {
        int respuesta_introducida=Integer.parseInt(jTextField1.getText());
        if(respuesta_introducida==op.getResultado())
        {
            puntuacion++;
            JOptionPane.showMessageDialog(rootPane, "Enhorabuena");
            actualizarPuntuacion();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Has fallado, era "+op.getResultado());
        }
        
        op=new Operacion();
        mostarOperacion();
        
    }
    
     private static void actualizarPuntuacion()
    {
        lbl_puntuacion.setText(String.valueOf(puntuacion));
    }
    
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    op=new Operacion();
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
                mostarOperacion();
                               
            }
        });
    }
private static void mostarOperacion()
{
    
    operando1.setText(String.valueOf(op.getOperando1()));
    operando2.setText(String.valueOf(op.getOperando2()));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_comprobar;
    private static javax.swing.JTextField jTextField1;
    private static javax.swing.JLabel lbl_puntuacion;
    private static javax.swing.JLabel operando1;
    private static javax.swing.JLabel operando2;
    private javax.swing.JLabel txt_suma;
    // End of variables declaration//GEN-END:variables
}
